get_event:
  path: /event
  controller: App\Controller\EventController::getEvent
  methods: [POST]
  
get_events:
  path: /events
  controller: App\Controller\EventController::getEvents
  methods: [GET]